### ISSUE TITLE
[Insight] The composer.json file should be valid

### ISSUE THREAD

**Issue by francescotrucchia** [ideatosrl/Idephix#22]
**[in composer.json](https://github.com/ideatosrl/Idephix/blob/master/composer.json)**
> description : is missing and it is required
_Posted from [SensioLabsInsight](https://insight.sensiolabs.com/projects/9cb2b89d-bc60-4676-9e6e-a6675a2a48c6/analyses/1)_

**Comment by ftassi** [comment]
This should be solved by 0eb67d
