### ISSUE TITLE
new Idephix($config, ...) instead of new Idephix($targets...)

### ISSUE THREAD

**Issue by danielsan80** [ideatosrl/Idephix#37]
Why not inject a config assoc array (containg targets) instead an arrray of tagets? Sometime you need to set configuration keys for tasks that play with the local environment only... for example.

**Comment by ftassi** [comment]
@danielsan80 configuration management is under refactoring. Have a look at http://idephix.readthedocs.io/en/latest/configuration.html as a starting point.
I'm closing this as the creation of Idephix instance is no longer a user responsibility. We may allow the users to define and inject some custom configuration item in the future.
