### ISSUE TITLE
Allow to specify idxfile

### ISSUE THREAD

**Issue by micheleorselli** [ideatosrl/Idephix#39]
In a CI/CD environment splitting build files by stage is a common practice. In idephix this is not possible atm since filename is hardcoded.

I propose to add a new option ```-f / --file``` in order do specify a given idxfile. The syntax would be something like that

```idx -f myidxfile.php [args]```

what do you think? @kea @ftassi @ricfrank @francescotrucchia

**Comment by francescotrucchia** [comment]
:+1:

**Comment by ricfrank** [comment]
+1

**Comment by ftassi** [comment]
:+1:

**Comment by ricfrank** [comment]
PR for this issue:

https://github.com/ideatosrl/Idephix/pull/43

Shippable is broken for php 5.3.3 env.
