### ISSUE TITLE
better config management

### ISSUE THREAD

**Issue by micheleorselli** [ideatosrl/Idephix#40]
As for now the whole idephix configuration is managed by a plain array eg.

```php
$targets = array(
    'test' => array(
        'hosts' => array('127.0.0.1'),
        'ssh_params' => array('user' => 'kea')
    ),
);
```

which is fine as long you don't need to modify dinamically one of the entries. One use case would be finding hosts ip dinamically by invoking aws api. One approach to solve this could be wrapping all the configurations in a ```Config``` o ```Context``` class which can ben injected in task a al symfony controllers

```php
$idx-> add('idephix:test-params', function (Context $ctx, $go = false) use ($idx) {
         $ctx->setHosts('192.168.56.101');
});
``` 

waiting for feedback @francescotrucchia @ftassi @ricfrank @kea

**Comment by ricfrank** [comment]
Do You think that Context class has to wrap $targets and expose an interface to modify $targets value?

**Comment by micheleorselli** [comment]
yep, something like that, I'm just shamelessly copy the idea from http://www.github.com/pyinvoke/invoke (which will be used in the next relase of fabric) and in particular http://docs.pyinvoke.org/en/0.10.1/getting_started.html#using-contexts and http://docs.pyinvoke.org/en/0.10.1/concepts/context.html#boilerplate-reduction

**Comment by drAlberT** [comment]
Why don't to think about YML config files for defining deployment environment?

I was watching to Magallanes (https://github.com/andres-montanez/Magallanes) and it is very simple to use and configure .. without having to be a smart php coder .. but its code is not .. emhh .. so robust :)

Can we get from that project whatever is good and implement in Idephix?

Just an idea :)

**Comment by ftassi** [comment]
@drAlberT why not, I'll look into it.
We've started working on some refactoring of the idxfile, have a look at #50 and #51

**Comment by drAlberT** [comment]
@ftassi great :)

My idea is:
- have idx config to be stored in a dir (something like `.idx` or `.idxrc`, I really hate to have my root dir polluted by a plethora of non-project files)
- have config in `YML` format in this directory, so users can handle config in a simpler way, not having to be a smart PHP coder (look forward and make idx a language-independent deploy tool)

PS:
@ftassi do you tried `Garofalo W350` ? :P

**Comment by micheleorselli** [comment]
Hi @drAlberT,
thanks for your suggestions, we'd like to make idephix as intuitive as possibile. My personal idea about that is: if you know PHP you should be able to write an idxfile without learning (almost) anything else. You don't need to be a smart php coder, just an average one ;-)

Regarding making idephix a language independent tool: other languages have well assessed tool, I'm thinking about fabric/invoke for python, rake/capistrano for ruby. Can idephix compete with those tools? It sounds cool, we'll see :-P

**Comment by ftassi** [comment]
@drAlberT I'm not sure about the directory. I agree that having a bunch of .configfile in the project root can be annoying (and nowadays we're using more and more of them), but would having a bunch of directories be a better scenario ?

Imho the default position for the config file should be `./`. That said the config position is, and it will be, customizable by a cli parameter.

*yes, I've tried W350 but we'll have to discuss about flours and :pizza:  somewhere else :stuck_out_tongue_winking_eye:*

**Comment by drAlberT** [comment]
@ftassi I was talking about a directory in case we split config in a tree of "environments", custom tasks and so on .. it is the good thing I'd get from magallanes 

Of course if there have to be only one config it has to be a file (.file - hidden on *n*x) :)

**Comment by drAlberT** [comment]
@micheleorselli have to read as a "by-design" flag? ;)

btw, if capistrano is for ruby why it exists capifony? ;)   Nowadays it lacks of good PHP-coded deploying tools .. the only alternatives I found are magallanes and idephix .. I'm only suggesting to take the best from both .. magallanes is simple and intuitive, idephix is well coded  ... 

Of course it is your project .. mine is just a suggestion :)

**Comment by ftassi** [comment]
@micheleorselli I'll send a PR for this soon. I've already introduced the concept of `Context`, it is just not exposed to the user right now. I guess at this point we should have all the tools to inject the current context at runtime
