### ISSUE TITLE
Shippable is broken

### ISSUE THREAD

**Issue by ricfrank** [ideatosrl/Idephix#44]
Shippable is broken for all PR. The problem is on php 5.3.3 build.

I think that problem is on phpenv-install. 

https://app.shippable.com/builds/552c3d4e6206490c0097364f

How we could fix it ?

**Comment by micheleorselli** [comment]
Are there any advantages on using that? We already have travis. I vote for removing this

**Comment by ricfrank** [comment]
I vote for removing, too.
