### ISSUE TITLE
simplify the release of a new idephix version

### ISSUE THREAD

**Issue by micheleorselli** [ideatosrl/Idephix#45]
Managing code and docs in two different branches is a pain in the a**. Releasing a new idephix phar is unnecessary complicated as it involves:
1. create the phar in the code branch
2. switch branch
3. add and commit the new phar
4. update the documentation, remembering what you've done in the other branch

I have some solution in mind
- [ ] drop github pages and switch to readthedocs or similar, managing only one repo
- [x] split docs and code repo

And in general, automating the release process with a Idephix script

**Comment by ftassi** [comment]
The website is now hosted at https://github.com/ideatosrl/getidephix.com
