### ISSUE TITLE
cache:clear is invoked after migrations execution

### ISSUE THREAD

**Issue by ProntoPro** [ideatosrl/Idephix#53]
cache:clear is invoked after migrations execution, this means that if install and configure the doctrine migration bundle after the first installation the new config.yml file is not loaded until the cache is cleared and the parameters describing migration paths are not accessibile resulting in a runtime error, this could happen on any command relying on configuration parameters that are loaded from cache.

**Comment by micheleorselli** [comment]
Aloha Mic, thanks for pointing that out. Basically you're suggesting to move the cache:clear operation before migration execution, is that right? I think that should be doable without problems

**Comment by ProntoPro** [comment]
Of  course.

--

*Michele Carino* | Tech lead

mobile:  +39 3332738806

skype:   michele.carino.ppro

email:    michele.carino@prontopro.it


<michele.carino@prontopro.it>

[image: Prontopro.it] <http://www.prontopro.it/>

www.prontopro.it
