### ISSUE TITLE
Exception "Destination file or directory exists" when switching from no shared_folders to some shared_folders

### ISSUE THREAD

**Issue by piribes** [ideatosrl/Idephix#55]
If you start doing releases without shared_folders and then you add something to it you get Exception.

>  [Exception]                                                                                                                    
>  Unable to link shared directory "/[...]/app/logs". Destination file or directory exists.

**Comment by ProntoPro** [comment]
Using the option shared_folders, if the folders were not yet present at the nth deploy (the one after introducing the condition) it is necessary to create them manually or to create a symlink.
