### ISSUE TITLE
I would like to preserve my current deploy dir after $releasesToKeep subsequent failing deploys

### ISSUE THREAD

**Issue by ProntoPro** [ideatosrl/Idephix#56]
I don't know if it is a feature or a joke, but after $releasesToKeep +1 subsequent failing deploys, the current directory will be erased.

**Comment by micheleorselli** [comment]
Indeed, that should be a nice feature to have :-P

Jokes apart, which version of idephix are you using? Is it installed via phar or composer? Do you have some logs?

**Comment by ProntoPro** [comment]
Logs apart our current directory have been throwed away we are pushing a fix  as soon as possible, we are on dev-master branch.
Logs are gone with the current direcotry. lol
Despite this we think idephix is an awesome tool, that is helping us to gain a lot of time.
