### ISSUE TITLE
idephix is no more compatible with the standard file format

### ISSUE THREAD

**Issue by fain182** [ideatosrl/Idephix#70]
Now that http://getidephix.com/idephix.phar is updated, my continuous integration fail because:

```
PHP Catchable fatal error:  Argument 1 passed to Idephix\Idephix::__construct() must be an instance of Idephix\Config, array given, called in /..../idxfile.php on line 18 and defined in phar:///..../idephix.phar/src/Idephix/Idephix.php on line 42
```

We can choose to stay compatible or not, but maybe we should add some documentation on how to migrate to the new format, or even better a hint inside idephix when is called in the wrong way.

**Comment by fain182** [comment]
I think the commit that is backward incompatible is 
https://github.com/ideatosrl/Idephix/commit/5613662204dcf2abac35d6c264cea78568317a48

**Comment by ftassi** [comment]
You can migrate your idx file (see http://idephix.readthedocs.io/en/latest/migrating_idx_file.html) or download rev 0.2.0 `curl http://getidephix.com/archive/idephix-0.2.0.phar > idephix.phar`
