### ISSUE TITLE
Show user defined tasks in a different section

### ISSUE THREAD

**Issue by micheleorselli** [ideatosrl/Idephix#72]
When showing the command line help user defined tasks are mixed with default idephix tasks such ad "selfupdate", "list", "init-id-file".

Showing user defined tasks in a separate section could add clarity, what do you guys think?

**Comment by ftassi** [comment]
We could use some prefix like idx: on command name. I'd like that.

Il 19 lug 2016 10:18 AM, "Michele Orselli" <notifications@github.com> ha
scritto:

**Comment by ftassi** [comment]
after a brief discussion with @micheleorselli we decided to implement some sort of customized list command that can split idx related commands from user defined commands, so we don't event need to use namespaces.

**Comment by ftassi** [comment]
@micheleorselli still interested in working on this?

**Comment by micheleorselli** [comment]
yup, I'd like to :-)
