### ISSUE TITLE
Write a "contribute" guide

### ISSUE THREAD

**Issue by ftassi** [ideatosrl/Idephix#79]
We need to ease contributions from our users, this is very important. 

We should write a brief introduction on how to contribute, which comprises tech stuff like coding standards but also info about our waffle kanban board, gitter chat and all the ways they can communivate with the @ideato team.

**Comment by micheleorselli** [comment]
we could follow github suggested practices for contributing: https://help.github.com/articles/setting-guidelines-for-repository-contributors/

also, references to waffle and gitter should be added in the readme.md
