### ISSUE TITLE
Env VS Target

### ISSUE THREAD

**Issue by ftassi** [ideatosrl/Idephix#82]
I think we should try to be more coherent on naming. 
We ask the user to define `targets` in his configuration file, but then we ask him to specify a `--env` parameter to select one. 

What do you think?

**Comment by micheleorselli** [comment]
it should really be "env" in the config file since values are normally something like "dev" "stage" "prod"

**Comment by ftassi** [comment]
I agree with you. I would also like to hear from @kea on  this
